runtime: nodejs12
service: default
automatic_scaling:
  max_instances: 5

handlers:
  - url: /
    secure: always
    static_files: build/index.html
    upload: build/index.html
  - url: /profile
    secure: always
    static_files: build/index.html
    upload: build/index.html
  - url: /
    secure: always
    static_dir: build
