# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
#   pull_request:
#     branches: [ main ]

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [12.x]
#         # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

#     steps:
#     - uses: actions/checkout@v2
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v1
#       with:
#         node-version: ${{ matrix.node-version }}
#     - run: npm ci
#     - run: npm start  
# #     - run: npm run build --if-present
# #    - run: npm test
jobs:
  deploy:
    name: "DEPLOY for: '${{github.ref}}'"
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1
      - name: Use Node.js (10.x)
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - run: sudo apt install npm
      - name: Running deploy for Testing
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: tranquil-marker-274412
          APPLICATION_CREDENTIALS:  ${{secrets.SERVICEACCOUNT}}
        with:
          args: app deploy App.yaml --project=tranquil-marker-274412
